name: Deploy Web Production

on:
  workflow_dispatch: {}

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  deploy_web:
    name: Deploy Web to Production
    type: deploy
    environment: production
    params:
      prod: true
